#define D_HTML_LANGUAGE "es"

#define _GRID_ "Red"
#define _SOLAR_ "Solar"
#define _BATTERY_ "Batería"
#define _INVERTERINFO_ "Datos Inversor"
#define _METERINFO_ "Datos Meter"
#define _OLEDPOWER_ "Potencia"
#define _VOLTAGE_ "Voltaje"
#define _CURRENT_ "Intensidad"
#define _IMPORT_ "CONSUMIDO"
#define _EXPORT_ "VERTIDO"
#define _OLEDTODAY_ "Hoy"
#define _START_ "Iniciando..."
#define _CONNECTING_ "Conectando..."
#define _RELAY_ "Salidas:"
#define _CONNECTSSID_ "CONÉCTESE AL SSID:"
#define _CONFIGPAGE_ "192.168.4.1"
#define _PRGRESTORE_ "Pulsa PRG para restablecer"
#define _WAIT_ "o espera 30 segundos"
#define _UPDATING_ "Actualizando, espere"
