#define D_HTML_LANGUAGE "pt"

#define _GRID_ "Rede"
#define _SOLAR_ "Solar"
#define _INVERTERINFO_ "Dados do inversor"
#define _METERINFO_ "Dados do medidor"
#define _OLEDPOWER_ "Potencia"
#define _VOLTAGE_ "Voltagem"
#define _CURRENT_ "Intensidade"
#define _IMPORT_ "CONSUMIDO"
#define _EXPORT_ "DISPONIBILIZADO"
#define _OLEDTODAY_ "HoJE"
#define _START_ "Iniciando..."
#define _CONNECTING_ "ligando..."
#define _RELAY_ "Saidas:"
#define _CONNECTSSID_ "LIGUE-SE AO SSID:"
#define _CONFIGPAGE_ "192.168.4.1"
#define _PRGRESTORE_ "Selecione PRG para ligar"
#define _WAIT_ "ou aguarde 30 segundos"
#define _UPDATING_ "Em atualização, aguarde"
